### ISSUE TITLE
Excessive memory usage using parallel backup

### ISSUE THREAD

**Issue by mnencia** [2ndquadrant-it/barman#116]
Backing up a very big database (21TB) using `parallel_jobs=2`, there was a huge increase in terms of memory used, compared to `parallel_jobs=1`. The issue mainly depend by the number of buckets generated by the copy.

I've reproduced it locally and I'm attaching the memory usage graph.

![oom-parallel](https://user-images.githubusercontent.com/104862/28518815-9ba61400-7069-11e7-9f72-7da5f82a9c6a.png)

**Comment by mnencia** [comment]
This is the memory usage graph of the same scenario and the patch applied.

![with-patch](https://user-images.githubusercontent.com/104862/28521963-5544c63e-7076-11e7-9119-95c591301274.png)

**Comment by icereval** [comment]
We've also observed similar high memory usage when running `recover` locally on the barman server, and the setting is not explicitly set to `parallel_jobs = 1` in the server configuration and `backup_method = postgres`.

**Comment by mnencia** [comment]
@icereval What Barman version are you using? This bug should have already been solved in the latest barman release (2.3).

**Comment by icereval** [comment]
@mnencia, I might have spoke too soon, we will keep monitoring but it appears our monitoring charts from GKE were incorrectly reporting all Memory on the host being used by the Barman container, further investigation show the memory utilization was normal.
