### ISSUE TITLE
Two small typo's in /faq/recovery/

### ISSUE THREAD

**Issue by mikesee** [2ndquadrant-it/barman#117]
while viewing the website I found a couple small typos on the following page:
http://www.pgbarman.org/faq/recovery/

In the HTML (title) tag, there is "F.A.Q. - Recovery a PstgreSQL database with Barman"  Postgresql is missing an O, and "Recovery" should probably just be "Recover" to read "F.A.Q. - Recover a Postgresql database with Barman"

It was suggested that I post an issue here to inform the project.
![2017-07-27 15_38_50-f a q - recovery a pstgresql database with barman](https://user-images.githubusercontent.com/730534/28693443-e9c41630-72e1-11e7-93e0-3b22d326c52c.png)

Cheers

**Comment by mikesee** [comment]
Just realized it could also have been meant to read "F.A.Q. - Recovery of a Postgresql database with Barman"
sorry for the extra message.

**Comment by mnencia** [comment]
Thanks for the notice. I've fixed the typo.
