### ISSUE TITLE
barman list-backup <server> show wal size as 0B for all but the first but seems to sum them all up

### ISSUE THREAD

**Issue by Underhunden** [2ndquadrant-it/barman#124]
I get slightly annoying (and scary) output from barman list-backup <server>. 

On server1 it seems to work correctly but not on server2.

[barman@backup-server ~]$ barman list-backup server1
server1 20170903T090502 - Mon Sep  4 04:45:18 2017 - Size: 8.0 TiB - WAL Size: 1.6 TiB
server1 20170827T090501 - Mon Aug 28 08:09:18 2017 - Size: 8.0 TiB - WAL Size: 2.3 TiB
server1 20170820T090502 - Mon Aug 21 04:28:22 2017 - Size: 7.9 TiB - WAL Size: 2.0 TiB
server1 20170813T090501 - Mon Aug 14 04:03:40 2017 - Size: 7.9 TiB - WAL Size: 2.4 TiB
server1 20170806T090502 - Mon Aug  7 08:11:45 2017 - Size: 8.0 TiB - WAL Size: 2.1 TiB

[barman@backup-server ~]$ barman list-backup server2
server2 20170901T173502 - Sun Sep  3 01:38:22 2017 - Size: 12.5 TiB - WAL Size: 6.0 TiB
server2 20170825T173501 - Sun Aug 27 02:12:19 2017 - Size: 11.4 TiB - WAL Size: 0 B
server2 20170818T173502 - Sat Aug 19 18:35:32 2017 - Size: 11.3 TiB - WAL Size: 0 B
server2 20170811T173502 - Sat Aug 12 19:46:03 2017 - Size: 11.1 TiB - WAL Size: 0 B

barman does not complain when trying to restore PITR from any of the backups from server2, so functionality seems to work. (This is not completely tested yet due to large backup sizes). The latest one does work however.

Version: Barman 2.2 (barman-2.2-1.rhel7.noarch)
OS: CentOS Linux release 7.3.1611 (Core)

**Comment by ShalbafZadeh** [comment]
@Underhunden how you perform backups ? 
is it manual of scheduled in a cron job?

use barman list-files for backups and check that do they contain any files?

**Comment by Underhunden** [comment]
Hi, we have "unfortunately" moved on to another backup solution for our bigger servers.

Thanks for checking up on it!
