### ISSUE TITLE
switch-xlog raises EXCEPTION: [Errno 13] Permission denied: 

### ISSUE THREAD

**Issue by seadba** [2ndquadrant-it/barman#126]
hello, testing barman on a single server - config looks ok but when i run an initial switch-xlog i get the following   - im wondering if the issue is the archive_command 

 barman switch-xlog --force --archive sqltest5
The WAL file 00000001000000000000009E has been closed on server 'sqltest5'
Waiting for the WAL file 00000001000000000000009E from server 'sqltest5' (max: 30 seconds)
EXCEPTION: [Errno 13] Permission denied: '/Instance1/postgres/barman/wal/00000001000000000000009B'
See log file for more details.

only failure in check is following

 barman check sqltest5
Server sqltest5
        WAL archive: FAILED (please make sure WAL shipping is setup)

 barman show-server sqltest5 | grep incoming
        incoming_wals_directory: /Instance1/postgres/barman/wal

 archive_command | test ! -f /Instance1/postgres/barman/wal/%f && cp %p /Instanc
e1/postgres/barman/wal/%f

 id barman
uid=1007(barman) gid=26(postgres) groups=26(postgres)

ls -lrt /Instance1/postgres/barman/
total 20
drwxrwxr-x. 2 barman postgres 4096 Sep  7 18:19 base
drwxrwxr-x. 2 barman postgres 4096 Sep  7 18:29 wals
drwxrwxr-x. 2 barman postgres 4096 Sep  7 18:29 errors
-rwxrwxr-x. 1 barman postgres    0 Sep  7 19:16 test.txt
drwxrwxr-x. 2 barman postgres 4096 Sep  8 09:38 wal
drwxrwxr-x. 2 barman postgres 4096 Sep  8 09:38 swal

ls -lrt /Instance1/postgres/barman/wal
total 65616
-rw-------. 1 pg10 postgres 16777216 Sep  7 19:21 00000001000000000000009B
-rw-------. 1 pg10 postgres 16777216 Sep  8 09:34 00000001000000000000009C
-rw-------. 1 pg10 postgres 16777216 Sep  8 09:38 00000001000000000000009D
-rw-------. 1 pg10 postgres 16777216 Sep  8 09:38 00000001000000000000009E

thanks

**Comment by gbartolini** [comment]
Hi @seadba, you are running Barman as a local setup, which is not recommended and supported. Also the issue you have highlighted goes beyond Barman and involves basic Linux system administration. I am closing this ticket. Thanks.
