### ISSUE TITLE
 barman backup Issue rsync

### ISSUE THREAD

**Issue by adnanhamdussalam** [2ndquadrant-it/barman#128]
Hi,

In my test envirnoment I have configured the barman backup on local server. While running the backup I am facing the below error:

-bash-4.2$ barman backup A0310TPGSQLSRV01
Starting backup using rsync-exclusive method for server A0310TPGSQLSRV01 in /home/barman/A0310TPGSQLSRV01/base/20170920T133551
Backup start at xlog location: 0/FE000028 (0000000100000000000000FE, 00000028)
This is the first backup for server A0310TPGSQLSRV01
WAL segments preceding the current backup have been found:
        0000000100000000000000FB from server A0310TPGSQLSRV01 has been removed
        0000000100000000000000FC from server A0310TPGSQLSRV01 has been removed
        0000000100000000000000FC.00000028.backup from server A0310TPGSQLSRV01 has been removed
Starting backup copy via rsync/SSH for 20170920T133551
ERROR: The backup has failed copying files
Asking PostgreSQL server to finalize the backup.
ERROR: Backup failed copying files.
DETAILS: data transfer failure
rsync error:
unexpected end of filter rule: P_
rsync error: syntax or usage error (code 1) at exclude.c(901) [client=3.0.9]
Processing xlog segments from file archival for A0310TPGSQLSRV01
        0000000100000000000000FD
        0000000100000000000000FE
        0000000100000000000000FE.00000028.backup

Your support is required.

Regards,

Adnan

**Comment by ShalbafZadeh** [comment]
@adnanhamdussalam paste archive_command from postgresql.conf file of A0310TPGSQLSRV01 please

**Comment by adnanhamdussalam** [comment]
Hi ShalbafZadeh,

The issue has been resolved. Found a test tablespace its datafiles were missing after dropping the test tablespace backup has been successful.

Thank you for your support.

Regards,

Adnan
