### ISSUE TITLE
backups failing rsync missing files

### ISSUE THREAD

**Issue by plockaby** [2ndquadrant-it/barman#13]
Backups are failing alarmingly often for us because of this error:

    2015-11-23 21:40:19,148 [21291] barman.backup ERROR: Backup failed copying files.
    DETAILS: data transfer failure on directory '/usr/local/pgsql/data'
    rsync error:
    ... list of files here ...
    rsync: link_stat "/usr/local/pgsql/data/base/pgsql_tmp/pgsql_tmp14179.115567" failed: No such file or directory (2)
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1505) [generator=3.0.6]

We are using Postgres 9.4.5, rsync 3.0.6, and barman 1.5.1. I see in the code that this is supposed to be ignored except that our backup definitely failed according to barman:

    postgres@xxx:/usr/lusers/plockaby$ barman list-backup xxx
    xxx 20151124T211803 - Tue Nov 24 21:50:25 2015 - Size: 38.5 GiB - WAL Size: 897.7 MiB
    xxx 20151123T211803 - FAILED
    xxx 20151122T211803 - Sun Nov 22 21:39:20 2015 - Size: 33.8 GiB - WAL Size: 20.0 GiB
    xxx 20151121T211804 - Sat Nov 21 21:38:43 2015 - Size: 33.4 GiB - WAL Size: 6.4 GiB
    xxx 20151120T211803 - FAILED
    xxx 20151119T211803 - FAILED
    xxx 20151119T171220 - Thu Nov 19 17:44:21 2015 - Size: 32.7 GiB - WAL Size: 15.6 GiB
    xxx 20151119T112806 - Thu Nov 19 11:44:58 2015 - Size: 32.5 GiB - WAL Size: 2.8 GiB

**Comment by gcalacoci** [comment]
Thank You for the report.

I will investigate on this issue. 

Regards. 

Giulio

**Comment by gcalacoci** [comment]
Could you please provide us a full log of the error? 
You can attach it to this ticket or send it via email at giulio.calacoci@2ndquadrant.it

Regards

**Comment by plockaby** [comment]
I've emailed you a log file that illustrates the errors from this issue as well as from #14 .

**Comment by plockaby** [comment]
Your answer was that the actual error was because there was a warning appearing in the rsync logs about the remote host not being known, which wouldn't cause rsync to throw a bad response code, but when combined with the other error it caused barman to get the error code and not know what the output meant. For example:

    Warning: Permanently added 'xxx.example.com' (RSA) to the list of known hosts.
    rsync: link_stat "/usr/local/pgsql/data/base/pgsql_tmp/pgsql_tmp14179.115567" failed: No such file or directory (2)
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1505) [generator=3.0.6]

This is because of a particular quirk about our systems where we have a process that blows away things that it is thought shouldn't be there. In this case, it blew away the `known_hosts` file. I've cleaned that up and all should be well. Thanks for looking into this.

**Comment by gcalacoci** [comment]
I think that this is the root of both your problems.
