### ISSUE TITLE
Arrow typo in documentation?

### ISSUE THREAD

**Issue by yerrysherry** [2ndquadrant-it/barman#136]
Hello,

Reading the documentation, I look at the figure:
Scenario 2: Backup via rsync/SSH (op page 13)

Here I see 2 red arrows pointing in the same direction (from pg to backup).

A little bit further I read:
2. an SSH connection for base backup operations to be used by rsync that allows the barman user
on the Barman server to connect as postgres user on the PostgreSQL server

I think the second must be pointing for backup to pg)?

Regards,
Gerrit

**Comment by gbartolini** [comment]
Hi @yerrysherry. I guess it depends on the point of view. If you want to emphasise the connection, you are right (but then we should also change pg_basebackup's direction in the previous diagram). We were actually focusing more on the payload (in this case the backup) that is transferred from the PostgreSQL server to the Barman server.

Thanks for pointing this out. It means that you really paid attention to the documentation (something not to take for granted these days!). I hope my answer resonates with you. Please close the ticket if so.
