### ISSUE TITLE
Using barman with repmgr: wal_level and other config params

### ISSUE THREAD

**Issue by sarfarazm** [2ndquadrant-it/barman#144]
We are setting up a new Primary/Standby Postgres cluster for our production environment. For streaming replication, we are using _repmgr_ in the '_hot_standby_' mode.

We are also using _barman_ in streaming backup mode for PITR.

This setup seems to be working without any apparent problems. I just have one query about  this.

The barman documentation says the following:

(ref: http://docs.pgbarman.org/release/2.3/)
> One configuration parameter that is crucially important is the wal_level parameter. This parameter must be configured to ensure that all the useful information necessary for a backup to be coherent are included in the transaction log file.
> 
> wal_level = 'replica'
> For PostgreSQL versions older than 9.6, wal_level must be set to hot_standby.

For hot_standby in repmgr, we need to set the wal_level as 'hot_standby'. 

Will this be a problem? Can it cause some information to be missing from barman backups that might give rise to issues during restore activity?

**Comment by ShalbafZadeh** [comment]
@sarfarazm 
as postgres 9.6 and beyond , hot_standby level is mapped to replica level
i think you shoud't encounter any problem

**Comment by gbartolini** [comment]
I am closing this ticket, as 'replica' - which has been introduced in 9.6 - works fine.

Quoting from https://www.postgresql.org/docs/10/static/runtime-config-wal.html - section about wal_level:

> In releases prior to 9.6, this parameter also allowed the values archive and hot_standby. These are still accepted but mapped to replica.
