### ISSUE TITLE
Allow to run scripts in background

### ISSUE THREAD

**Issue by jorsol** [2ndquadrant-it/barman#147]
Pre/post backup hook scripts are great to extend the behavior of Barman, but they run sequentially and blocks when using backup all.

I would like to run a post-script in background since is a long running task of compression.

**Comment by mnencia** [comment]
You just need to write a script that spawns a background process and terminate immediately.

You can do it in sh using the `&` operator.

    your-long-running-job &

**Comment by jorsol** [comment]
Yeah, it used to be like that, but something in version 2.x changed and now it does not work anymore, it stills spawns the process but the barman process blocks until the script finish.

**Comment by mnencia** [comment]
Understood. Your script keeps some descriptor open. You can solve it by redirecting the communications to a log file:

    your-long-running-job < /dev/null > /path/to/file.log 2>&1 &

**Comment by jorsol** [comment]
Thanks for the quick reply.
