### ISSUE TITLE
Using `archive_timeout` to prevent corner case with concurrent backup

### ISSUE THREAD

**Issue by gciolli** [2ndquadrant-it/barman#182]
We could suggest using this parameter to ensure enough WAL file switching even when using concurrent backups.

**Comment by mnencia** [comment]
It will not work. The corner case can only happen in the first backup when no previous backup is available, and Barman has been just configured. There is no way to prevent that other than failing the backup as soon as we can detect that condition, that unfortunately is at the end of the backup.
