### ISSUE TITLE
streaming_archiver and streaming_conninfo not working 

### ISSUE THREAD

**Issue by damnski** [2ndquadrant-it/barman#20]
Hi,

I am using 1.6.0a1 to get the pg_receivexlog working with postgresql 9.3 on centos7.  I have my configuration attached.  I manually attempted the pg_receivexlog as the barman user with success.  I can 'barman check server0' - I see a successful connection in the postgres log and the output shows: "pg_receivexlog: OK" and "pg_receivexlog compatible: OK".  

'barman cron' does not make a connection, though it outputs: "Starting WAL archiving for server server0".

Thanks,
-dkw

[config.txt](https://github.com/2ndquadrant-it/barman/files/62577/config.txt)

[diagnose.txt](https://github.com/2ndquadrant-it/barman/files/62691/diagnose.txt)

**Comment by gbartolini** [comment]
Hi,

  this feature it is currently being developed. What you currently see in the master branch, is the basis for future development. The plan includes adding a 'receive-wal' command that starts pg_receivexlog and receives WAL files through streaming protocol.

  Stay tuned.

Cheers,
Gabriele
