### ISSUE TITLE
Recovery Retry Script doesn't get passed the recovery environment

### ISSUE THREAD

**Issue by dragonfyre13** [2ndquadrant-it/barman#204]
The current recovery retry script doesn't get passed the recovery environment due to a typo in backup.py, it's reapplying the environment to the original recovery_script's "script" variable, rather than the "retry_script" variable.

This means recovery retry scripts don't get environment variables passed to them

I created a pull request (#203) to resolve, but this seems a pretty straightforward bug.

**Comment by gbartolini** [comment]
Closes as merged pull request #203
