### ISSUE TITLE
Backup Bug - Not terminating, still in STARTED state

### ISSUE THREAD

**Issue by Ele-M-ent** [2ndquadrant-it/barman#211]
Hi Team,

I have an issue when I want to make a backup of my postgresql instance.

As you can see in the title, the backup stay in STARTED state, and even when I stop the backup process by typing "select pg_stop_backup();" on the postgresql server. I verified that the backup was well stopped on the postgres server side by typing "SELECT pg_is_in_backup();" and the command returns false.

**# Informations** 
- I have a a postgres server and a barman server.
- postgresql version : 9.6

**# postgresql config**

![postgresql_config](https://user-images.githubusercontent.com/7704022/55816960-bfa00980-5af3-11e9-97b7-c4a7d3056bb9.PNG)

**# barman config** 

[cwfr-prod-db3]

description =  "MASTER DB3 Server"

ssh_command = ssh postgres@cwfr-prod-db3

;To test (as barman user) : psql 'host=cwfr-prod-db3 user=barman dbname=cwallet'
conninfo = host=cwfr-prod-db3 user=barman dbname=cwallet

;Backup directory
backup_directory = /media/barmanstore/cwfr-prod-db3

;backup_method = rsync
archiver = on

; Set the incremental backup based on the last full backup
reuse_backup = link

; Checkpointing ensures any modified data in PostgreSQL's memory cache are written to data files
immediate_checkpoint = true

; Barman will try to connect to the PostgreSQL server three times if the copy operation fails
basebackup_retry_times = 3

; There will be a 30-second delay between each retry
basebackup_retry_sleep = 30

; Check that the last backup is not more that 1 days old
last_backup_maximum_age = 1 DAYS

; Keep the last 7 days archive WAL
retention_policy_mode = auto
retention_policy = RECOVERY WINDOW OF 7 DAYS
wal_retention_policy = main

; Ensure that we have at least 2 base backups
minimum_redundancy = 2

;WAL compress type
compression = bzip2

**# barman diagnose**

barman@cwfr-prod-pgbarman:~$ barman diagnose
{
    "global": {
        "config": {
            "barman_home": "/media/barmanstore", 
            "barman_user": "barman", 
            "basebackup_retry_sleep": "30", 
            "basebackup_retry_times": "3", 
            "compression": "gzip", 
            "configuration_files_directory": "/etc/barman.d", 
            "errors_list": [], 
            "immediate_checkpoint": "true", 
            "last_backup_maximum_age": "1 DAYS", 
            "log_file": "/var/log/barman/barman.log", 
            "log_level": "DEBUG"
        }, 
        "system_info": {
            "barman_ver": "2.2", 
            "kernel_ver": "Linux cwfr-prod-pgbarman 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux", 
            "python_ver": "", 
            "release": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 16.04.3 LTS\nRelease:\t16.04\nCodename:\txenial", 
            "rsync_ver": "rsync  version 3.1.1  protocol version 31", 
            "ssh_ver": ""
        }
    }, 
    "servers": {
        "cwfr-prod-db3": {
            "backups": {
                "20190319T140318": {
                    "backup_id": "20190319T140318", 
                    "backup_label": null, 
                    "begin_offset": 44688, 
                    "begin_time": "Tue Mar 19 14:03:18 2019", 
                    "begin_wal": "0000000100000074000000B2", 
                    "begin_xlog": "74/B200AE90", 
                    "config_file": "/etc/postgresql/9.6/main/postgresql.conf", 
                    "copy_stats": null, 
                    "deduplicated_size": null, 
                    "end_offset": null, 
                    "end_time": null, 
                    "end_wal": null, 
                    "end_xlog": null, 
                    "error": null, 
                    "hba_file": "/etc/postgresql/9.6/main/pg_hba.conf", 
                    "ident_file": "/etc/postgresql/9.6/main/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "rsync-exclusive", 
                    "pgdata": "/media/postgres/postgresql/9.6/main", 
                    "server_name": "cwfr-prod-db3", 
                    "size": null, 
                    "status": "STARTED", 
                    "tablespaces": null, 
                    "timeline": 1, 
                    "version": 90612, 
                    "xlog_segment_size": 16777216
                }
            }, 
            "config": {
                "active": true, 
                "archiver": true, 
                "archiver_batch_size": 0, 
                "backup_directory": "/media/barmanstore/cwfr-prod-db3", 
                "backup_method": "rsync", 
                "backup_options": "exclusive_backup", 
                "bandwidth_limit": null, 
                "barman_home": "/media/barmanstore", 
                "barman_lock_directory": "/media/barmanstore", 
                "basebackup_retry_sleep": 30, 
                "basebackup_retry_times": 3, 
                "basebackups_directory": "/media/barmanstore/cwfr-prod-db3/base", 
                "check_timeout": 30, 
                "compression": "bzip2", 
                "conninfo": "host=cwfr-prod-db3 user=barman dbname=cwallet", 
                "custom_compression_filter": null, 
                "custom_decompression_filter": null, 
                "description": "MASTER DB3 Server", 
                "disabled": false, 
                "errors_directory": "/media/barmanstore/cwfr-prod-db3/errors", 
                "immediate_checkpoint": true, 
                "incoming_wals_directory": "/media/barmanstore/cwfr-prod-db3/incoming", 
                "last_backup_maximum_age": "1 day", 
                "max_incoming_wals_queue": null, 
                "minimum_redundancy": 2, 
                "msg_list": [], 
                "name": "cwfr-prod-db3", 
                "network_compression": false, 
                "parallel_jobs": 1, 
                "path_prefix": null, 
                "post_archive_retry_script": null, 
                "post_archive_script": null, 
                "post_backup_retry_script": null, 
                "post_backup_script": null, 
                "pre_archive_retry_script": null, 
                "pre_archive_script": null, 
                "pre_backup_retry_script": null, 
                "pre_backup_script": null, 
                "recovery_options": "", 
                "retention_policy": "window 7 d", 
                "retention_policy_mode": "auto", 
                "reuse_backup": "link", 
                "slot_name": null, 
                "ssh_command": "ssh postgres@cwfr-prod-db3", 
                "streaming_archiver": false, 
                "streaming_archiver_batch_size": 0, 
                "streaming_archiver_name": "barman_receive_wal", 
                "streaming_backup_name": "barman_streaming_backup", 
                "streaming_conninfo": "host=cwfr-prod-db3 user=barman dbname=cwallet", 
                "streaming_wals_directory": "/media/barmanstore/cwfr-prod-db3/streaming", 
                "tablespace_bandwidth_limit": null, 
                "wal_retention_policy": "simple-wal 7 d", 
                "wals_directory": "/media/barmanstore/cwfr-prod-db3/wals"
            }, 
            "status": {
                "archive_command": "rsync -a %p barman@cwfr-prod-pgbarman:/media/barmanstore/cwfr-prod-db3/incoming/%f", 
                "archive_mode": "on", 
                "archived_count": 13268, 
                "config_file": "/etc/postgresql/9.6/main/postgresql.conf", 
                "current_archived_wals_per_second": 0.00475764633517858, 
                "current_size": 260091923286.0, 
                "current_xlog": "00000001000000980000001E", 
                "data_directory": "/media/postgres/postgresql/9.6/main", 
                "failed_count": 1122, 
                "hba_file": "/etc/postgresql/9.6/main/pg_hba.conf", 
                "ident_file": "/etc/postgresql/9.6/main/pg_ident.conf", 
                "is_archiving": true, 
                "is_superuser": true, 
                "last_archived_time": "Tue Apr  9 18:18:01 2019", 
                "last_archived_wal": "00000001000000980000001D", 
                "last_failed_time": "Thu Mar 14 10:20:59 2019", 
                "last_failed_wal": "000000010000006C00000003", 
                "pgespresso_installed": false, 
                "replication_slot": null, 
                "replication_slot_support": true, 
                "server_txt_version": "9.6.12", 
                "stats_reset": "Thu Mar  7 11:40:13 2019", 
                "synchronous_standby_names": [
                    ""
                ], 
                "wal_level": "replica"
            }, 
            "system_info": {
                "kernel_ver": "Linux cwfr-prod-db3 4.15.0-1037-azure #39~16.04.1-Ubuntu SMP Tue Jan 15 17:20:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux", 
                "python_ver": "", 
                "release": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 16.04.5 LTS\nRelease:\t16.04\nCodename:\txenial", 
                "rsync_ver": "rsync  version 3.1.1  protocol version 31", 
                "ssh_ver": ""
            }, 
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000001": {
                        "compression": "bzip2", 
                        "name": "00000001000000980000001D", 
                        "size": 5341374, 
                        "time": 1554826680.592972
                    }
                }
            }
        }
    }
}

Thanks a lot for your help guys,
Regards,
Valentin

**Comment by mnencia** [comment]
This looks like a bug (#199)  that has been solved in the latest barman release.

Barman 2.2 is very old and has a lot of bugs. Please try again with the latest Barman version (2.7).

It is sufficient to install the latest package from https://sourceforge.net/projects/pgbarman/files/2.7/ or https://apt.2ndquadrant.com
