### ISSUE TITLE
Does barman really need superuser?

### ISSUE THREAD

**Issue by slavniyteo** [2ndquadrant-it/barman#213]
Hi, thank you for developing and supporting barman.

I know about this 3-years old decision: #30. 

But in my opinion we can do the job without superuser credentials because of replication user already have enough permissions in order to do almost everything we need. 

I say `almost` because replication user isn't allowed to call the `pg_switch_wal` function. We just call `GRANT EXECUTE ON FUNCTION pg_switch_wal TO repl_user;` and it's done. The list of all permissions I had to grant to replication user:

```sql
GRANT EXECUTE ON FUNCTION pg_switch_wal TO repl_user;
GRANT pg_read_all_settings TO repl_user;
GRANT CREATE ON TABLESPACE pg_global TO repl_user;
GRANT EXECUTE ON FUNCTION pg_create_restore_point TO repl_user;
``` 

Of course, there should be another functions that replication user unallowed to execute. But I'd better grant few privileges to replication user instead of expose superuser to danger.

Maybe we can omit some functionality in order not to grant replication user too many permissions (as instance, making checkpoint before backup).

---

I'm not an expert in postgresql so there may be another reasons that I do not understand yet. If so, sorry for rising this topic up again.

**Comment by RajKiranS** [comment]
Hi Barman team,

Yes, in production environments people would feel little skeptical to grant `super` user access to what ever account Barman is running with. Could you please remove the `superuser` check from `barman check` and also reply if the additional perms specified by @slavniyeto are enough?

Thanks again for Barman. Its just wonderful.
