### ISSUE TITLE
Error on ConsoleOutputWriter after upgrading to 2.7

### ISSUE THREAD

**Issue by reichert** [2ndquadrant-it/barman#219]
Hi guys,

after upgrading to 2.7 some console commands stopped working with a message telling that ConsoleOutputWriter does not support the XXXX command.

The most commands still works. Here are two that gave me the exception.

Example:

$ barman list-server
EXCEPTION: The ConsoleOutputWriter writer does not support the "list_server" command

$ barman status db1
Server db1:
EXCEPTION: The ConsoleOutputWriter writer does not support the "status" command
$

Regards.

**Comment by mnencia** [comment]
Could you please add some more information?

What distribution are you using? Is there any backtrace in the barman log? From which source you installed the barman packages? If it works, please also attach the output of `barman diagnose` command.

Thanks

**Comment by reichert** [comment]
Of course, thanks for the reply.
I'm using ubuntu 18.04 in EC2. I installed it through apt-get of the ubuntu.

At the logs I can see the problem:
2019-04-22 20:45:43,649 [21084] barman.output ERROR: The ConsoleOutputWriter writer does not support the "status" command
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 296, in result
    _dispatch(_writer, 'result', command, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 169, in _dispatch
    return handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 781, in result_status
    self.info("\t%s: %s", description, message)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 429, in info
    self._out(message, args)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 393, in _out
    self._print(message, args, sys.stdout)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 380, in _print
    encoded_msg = _format_message(message, args).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128)

Perhaps the output of locale may help:
barman@barman:/var/log/barman$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

The barman diagnose below:
barman@barman:/var/log/barman$ barman diagnose
{
    "global": {
        "config": {
            "barman_home": "/mnt/backup/barman", 
            "barman_user": "barman", 
            "configuration_files_directory": "/etc/barman.d", 
            "errors_list": [], 
            "log_file": "/var/log/barman/barman.log", 
            "log_level": "INFO", 
            "retention_policy": "RECOVERY WINDOW OF 5 WEEKS"
        }, 
        "system_info": {
            "barman_ver": "2.7", 
            "kernel_ver": "Linux pgpool2 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux", 
            "python_ver": "", 
            "release": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 18.04.2 LTS\nRelease:\t18.04\nCodename:\tbionic", 
            "rsync_ver": "rsync  version 3.1.2  protocol version 31", 
            "ssh_ver": ""
        }
    }, 
    "servers": {
        "db1": {
            "backups": {
                "20190308T022221": {
                    "backup_id": "20190308T022221", 
                    "backup_label": null, 
                    "begin_offset": 40, 
                    "begin_time": "Fri Mar  8 02:22:28 2019", 
                    "begin_wal": "000000010000000500000009", 
                    "begin_xlog": "5/9000028", 
                    "config_file": "/etc/postgresql/11/db1/postgresql.conf", 
                    "copy_stats": {
                        "copy_time": 1859.949305, 
                        "total_time": 1859.949305
                    }, 
                    "deduplicated_size": 23915982732, 
                    "end_offset": 96, 
                    "end_time": "Fri Mar  8 02:53:21 2019", 
                    "end_wal": "00000001000000050000000A", 
                    "end_xlog": "5/A000060", 
                    "error": null, 
                    "hba_file": "/etc/postgresql/11/db1/pg_hba.conf", 
                    "ident_file": "/etc/postgresql/11/db1/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "postgres", 
                    "pgdata": "/mnt/db1/postgresql/11/main", 
                    "server_name": "db1", 
                    "size": 23915982732, 
                    "status": "DONE", 
                    "tablespaces": null, 
                    "timeline": 1, 
                    "version": 110002, 
                    "xlog_segment_size": 16777216
                }, 
                "20190420T000057": {
                    "backup_id": "20190420T000057", 
                    "backup_label": null, 
                    "begin_offset": 40, 
                    "begin_time": "Sat Apr 20 00:01:09 2019", 
                    "begin_wal": "0000000100000018000000D9", 
                    "begin_xlog": "18/D9000028", 
                    "config_file": "/etc/postgresql/11/db1/postgresql.conf", 
                    "copy_stats": {
                        "copy_time": 5046.173895, 
                        "total_time": 5046.173895
                    }, 
                    "deduplicated_size": 28410130322, 
                    "end_offset": 0, 
                    "end_time": "Sat Apr 20 01:25:03 2019", 
                    "end_wal": "0000000100000018000000DB", 
                    "end_xlog": "18/DC000000", 
                    "error": null, 
                    "hba_file": "/etc/postgresql/11/db1/pg_hba.conf", 
                    "ident_file": "/etc/postgresql/11/db1/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "postgres", 
                    "pgdata": "/mnt/db1/postgresql/11/main", 
                    "server_name": "db1", 
                    "size": 28410130322, 
                    "status": "DONE", 
                    "tablespaces": null, 
                    "timeline": 1, 
                    "version": 110002, 
                    "xlog_segment_size": 16777216
                }
            }, 
            "config": {
                "active": true, 
                "archiver": false, 
                "archiver_batch_size": 0, 
                "backup_directory": "/mnt/backup/barman/db1", 
                "backup_method": "postgres", 
                "backup_options": "concurrent_backup", 
                "bandwidth_limit": null, 
                "barman_home": "/mnt/backup/barman", 
                "barman_lock_directory": "/mnt/backup/barman", 
                "basebackup_retry_sleep": 30, 
                "basebackup_retry_times": 0, 
                "basebackups_directory": "/mnt/backup/barman/db1/base", 
                "check_timeout": 30, 
                "compression": "gzip", 
                "conninfo": "host=db1 user=barman dbname=postgres", 
                "custom_compression_filter": null, 
                "custom_decompression_filter": null, 
                "description": "Servidor produ\u00e7\u00e3o master (Streaming-Only)", 
                "disabled": false, 
                "errors_directory": "/mnt/backup/barman/db1/errors", 
                "immediate_checkpoint": false, 
                "incoming_wals_directory": "/mnt/backup/barman/db1/incoming", 
                "last_backup_maximum_age": null, 
                "max_incoming_wals_queue": null, 
                "minimum_redundancy": 0, 
                "msg_list": [], 
                "name": "db1", 
                "network_compression": false, 
                "parallel_jobs": 1, 
                "path_prefix": null, 
                "post_archive_retry_script": null, 
                "post_archive_script": null, 
                "post_backup_retry_script": null, 
                "post_backup_script": null, 
                "post_delete_retry_script": null, 
                "post_delete_script": null, 
                "post_recovery_retry_script": null, 
                "post_recovery_script": null, 
                "post_wal_delete_retry_script": null, 
                "post_wal_delete_script": null, 
                "pre_archive_retry_script": null, 
                "pre_archive_script": null, 
                "pre_backup_retry_script": null, 
                "pre_backup_script": null, 
                "pre_delete_retry_script": null, 
                "pre_delete_script": null, 
                "pre_recovery_retry_script": null, 
                "pre_recovery_script": null, 
                "pre_wal_delete_retry_script": null, 
                "pre_wal_delete_script": null, 
                "primary_ssh_command": null, 
                "recovery_options": "", 
                "retention_policy": "window 5 w", 
                "retention_policy_mode": "auto", 
                "reuse_backup": null, 
                "slot_name": "barman", 
                "ssh_command": null, 
                "streaming_archiver": true, 
                "streaming_archiver_batch_size": 0, 
                "streaming_archiver_name": "barman_receive_wal", 
                "streaming_backup_name": "barman_streaming_backup", 
                "streaming_conninfo": "host=db1 user=streaming_barman", 
                "streaming_wals_directory": "/mnt/backup/barman/db1/streaming", 
                "tablespace_bandwidth_limit": null, 
                "wal_retention_policy": "simple-wal 5 w", 
                "wals_directory": "/mnt/backup/barman/db1/wals"
            }, 
            "status": {
                "config_file": "/etc/postgresql/11/db1/postgresql.conf", 
                "connection_error": null, 
                "current_size": 28675467847.0, 
                "current_xlog": "0000000100000019000000FF", 
                "data_directory": "/mnt/db1/postgresql/11/main", 
                "hba_file": "/etc/postgresql/11/db1/pg_hba.conf", 
                "ident_file": "/etc/postgresql/11/db1/pg_ident.conf", 
                "is_in_recovery": false, 
                "is_superuser": true, 
                "pg_basebackup_bwlimit": true, 
                "pg_basebackup_compatible": true, 
                "pg_basebackup_installed": true, 
                "pg_basebackup_path": "/usr/bin/pg_basebackup", 
                "pg_basebackup_tbls_mapping": true, 
                "pg_basebackup_version": "11.2-1.pgdg16.04+1)", 
                "pg_receivexlog_compatible": true, 
                "pg_receivexlog_installed": true, 
                "pg_receivexlog_path": "/usr/bin/pg_receivewal", 
                "pg_receivexlog_supports_slots": true, 
                "pg_receivexlog_synchronous": false, 
                "pg_receivexlog_version": "11.2-1.pgdg16.04+1)", 
                "pgespresso_installed": false, 
                "replication_slot": [
                    "barman", 
                    true, 
                    "19/FF000000"
                ], 
                "replication_slot_support": true, 
                "server_txt_version": "11.2", 
                "streaming": true, 
                "streaming_supported": true, 
                "synchronous_standby_names": [
                    ""
                ], 
                "systemid": "6665861654435929163", 
                "timeline": 1, 
                "wal_level": "replica", 
                "xlogpos": "19/FF469BD8"
            }, 
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000001": {
                        "compression": "gzip", 
                        "name": "0000000100000019000000FE", 
                        "size": 4845242, 
                        "time": 1555976687.47741
                    }
                }
            }
        }
    }
}

**Comment by reichert** [comment]
I just realized that it was because we have a character like ç in the server description (config.description in the diagnose above). I think this should be treated in the encode/decode to utf-8 of the _print method.
Regards.

**Comment by mnencia** [comment]
Thanks for the report. That's definitely a bug. We will fix it in the next release.

**Comment by reichert** [comment]
> Thanks for the report. That's definitely a bug. We will fix it in the next release.

Thank you for your prompt reply!
Regards.

**Comment by mnencia** [comment]
This issue has been closed with 8b8d466d645ae58716005e866fb0185f90aeb2ad and 0459acbbd8608e558405d9ee28cc912032c11fbe
