### ISSUE TITLE
EXCEPTION: 'str' object has no attribute 'backup_id'

### ISSUE THREAD

**Issue by gcalacoci** [2ndquadrant-it/barman#22]
Trying to remove a backup from a server, barman exit with the following exception:
`EXCEPTION: 'str' object has no attribute 'backup_id'`

How to replicate the error:

* Perform a full backup on a server
* Start a new backup on the same server
* Try to remove a backup the first backup while the backup is still running

**Comment by Tozzje** [comment]
I can confirm this issue. This happend here while "barman backup all"  was still running.
