### ISSUE TITLE
Barman exporter for Prometheus

### ISSUE THREAD

**Issue by WoLpH** [2ndquadrant-it/barman#220]
Not sure if this something that would be useful to others but I've written a little script to export the barman data to Prometheus so they can be viewed with Grafana:
https://gist.github.com/WoLpH/f569ba733499a67f1179be97ff69825b

Example output:
![image](https://user-images.githubusercontent.com/270571/56599957-f861d780-65f7-11e9-8ebc-6fb708daa484.png)

**Comment by WoLpH** [comment]
I should note that the script is slightly hacky in a few places because it has to resort to a bit of string parsing. In a few cases I couldn't find any options within barman to get actual values instead of strings without copying a bunch of code.

**Comment by ahes** [comment]
Similar exporter can be found here: https://github.com/ahes/prometheus-barman-exporter
Still waiting for `JsonOutputWriter()` or Python API for Barman to not parse CLI output.

**Comment by ahes** [comment]
@WoLpH JsonOutputWriter() done #234 ;)

**Comment by WoLpH** [comment]
Awesome! Excellent work, both the JSON output and the exporter look great. I guess we don't need this issue anymore

**Comment by anarcat** [comment]
couldn't we get those stats natively, i.e. merge OpenMetrics/Prometheus support directly in Barman instead of having to run Yet Another Exporter (pronounced "yaaaawwwn") ? :)
