### ISSUE TITLE
Skip Missing WAL (or Redo Backup Configuration)

### ISSUE THREAD

**Issue by saifulmuhajir** [2ndquadrant-it/barman#223]
Hi,

I came across this problem where WAL is accidentally missing (maybe deleted by someone) from the Postgres server and now Barman is complaining, obviously.

```
(dbbackup) $ barman receive-wal hive
Starting receive-wal for server hive
hive: pg_receivewal: starting log streaming at 7/AC000000 (timeline 1)
hive: pg_receivewal: unexpected termination of replication stream: ERROR:  requested WAL segment 0000000100000007000000AC has already been removed
hive: pg_receivewal: disconnected
ERROR: ArchiverFailure:pg_receivexlog terminated with error code: 1
```

How do I skip the missing WAL? Or, redo the setup of barman for this cluster, as in starting fresh?
Thanks

**Comment by jeffjanes** [comment]
Running: 

    barman receive-wal --reset hive

Will let you start streaming again.  Of course it also invalidates your existing backups for use other than PITR to before the break happened.
