### ISSUE TITLE
replication-status does not show hot-standby's

### ISSUE THREAD

**Issue by cfriedli** [2ndquadrant-it/barman#226]
Since the upgrade from 2.7 to 2.8 replication-status does not show any hot-standby's.

**barman replication-status acme  --minimal**                                                     
Streaming clients for master 'acme' (********************):                                                      
  1. W) ***@****** *************************3

**pg_stat_replication on acme:**
postgres=# select * from pg_stat_replication;
-[ RECORD 1 ]----+------------------------------
pid              | *******
usesysid         | *******
usename          | *******
application_name | database
client_addr      | *********
client_hostname  |
client_port      | *****************
backend_start    | *****************
backend_xmin     | *****************
state            | streaming
sent_location    | **************
write_location   | **************
flush_location   | **************
replay_location  | **************
sync_priority    | *****
sync_state       | *****
-[ RECORD 2 ]----+------------------------------
pid              | *************
usesysid         | *************
usename          | *************
application_name | barman_receive_wal
client_addr      | *************
client_hostname  |
client_port      | *************
backend_start    | *************

 
**Installed Packages:**
barman-2.8-1.rhel7.noarch
barman-cli-2.8-1.rhel7.noarch
postgresql96-9.6.13-1PGDG.rhel7.x86_64

**Comment by mnencia** [comment]
already fixed in 04e2383180373420699ef5ac83c80fd78791532b
