### ISSUE TITLE
Some enviroment variables does not get passed to wal_delete_retry hook scripts 

### ISSUE THREAD

**Issue by razielleizar** [2ndquadrant-it/barman#241]
Folowing enviroment variables doesn`t get passed due to mistakes in code:
BARMAN_SEGMENT
BARMAN_FILE
BARMAN_SIZE
BARMAN_TIMESTAMP
BARMAN_COMPRESSION
Pull request for bugfix: #240

**Comment by gbartolini** [comment]
Closed as #240 was merged
