### ISSUE TITLE
Store the system identifier

### ISSUE THREAD

**Issue by gbartolini** [2ndquadrant-it/barman#246]
We can collect the system identifier and store it in the barman server directory and block any operation if it does not match the connection one.

**Comment by georg-h** [comment]
Would this also cover multi-cluster server? 
We have a database server that has 14 PG clusters that are backed up by the same barman installation.
In case the "system identifier" is only based on the host whithout taking the cluster into account it wouldn't help that much.

regards 
Georg

**Comment by gbartolini** [comment]
It is the PostgreSQL system identifier, meaning that in a physical replication cluster they are all the same.
