### ISSUE TITLE
Backup Fails with Large 700 GB Database with no errors

### ISSUE THREAD

**Issue by uglycoder99** [2ndquadrant-it/barman#261]
This issue is almost exactly the same as issue #256.

Barman seems to be configured correctly but when I run the backup the entire 700GB is synced over and then the backup fails.  The only error barman shows is "error": "failure copying files ([Errno 5] Input/output error)".  

I have noticed that postgresql on the server being backed up will throw an error when pg_stop_backup is called indicating the backend has been terminated but there does not seem to be a reason it terminated.
" barman@postgres WARNING: aborting backup due to backend exiting before pg_stop_backup was called"

I have attached the output of Diagnose and Check.  Please let me know if you need any additional information.

[diagnose.txt](https://github.com/2ndquadrant-it/barman/files/4010194/diagnose.txt)
[check.txt](https://github.com/2ndquadrant-it/barman/files/4010206/check.txt)

Thanks,
 Justin

**Comment by uglycoder99** [comment]
So I set this aside for much of 2020 but spent the last week tracking it down.  It would appear that this particular error is related to running the backup command from the terminal and using the & to run it in the background.  Specifically, the sys.stdout association between the barman backup process and the console/logfile broke because of how I was running the backup.

I was attempting to test a backup using a command similar to the following:
barman backup pg &

running this backup instead from the barman cron file in cron.d made everything work as the sys.stdout did not get disconnected.

Justin

**Comment by amenonsen** [comment]
Wow, that's a pretty interesting failure mode. I would not have guessed that the "Input/output error" referred to sys.stdout! Thanks for the update.
