### ISSUE TITLE
python-barman RPM package should obsolete python2-barman package

### ISSUE THREAD

**Issue by dkacar-oradian** [2ndquadrant-it/barman#264]
I don't see spec files in the repository, so I'm not sure this is the right place to report this, but I don't know of another place.

I have CentOS 7 machines with `barman-cli` 2.9 packages from `pgdg11` repository. When I attempt to upgrade to 2.10 package `python-barman-2.10-1.rhel7.noarch` is pulled as a dependency. But the whole combo fails to install because files in `python-barman` package are trying to overwrite files from `python2-barman` package and package manager doesn't allow that.

The spec file for `python-barman` package should have:

```
Obsoletes: python2-barman
```
directive and then the package manager would remove `python2-barman` and install `python-barman` without problems.

Maybe there should also be `Conflicts` directive, but I didn't test that.

**Comment by L-Bd** [comment]
Is this just from the postgresql repo (via yum.postgresql.org), rather than the 2ndquadrant one?
Might be worth raising a ticket at https://redmine.postgresql.org/ if the packaging needs amending there.

**Comment by dkacar-oradian** [comment]
Thanks for the pointer. I've reported the problem there.
2ndquadrant repo doesn't suffer from that problem, as far as I can see with a cursory look.
This issue can be cloesed as not applicable, I think.
