### ISSUE TITLE
barman check shows empty incoming directory: FAILED

### ISSUE THREAD

**Issue by dangelsaurus** [2ndquadrant-it/barman#269]
brand new installation following instructions at http://docs.pgbarman.org/release/2.10/

running `barman check node1` everything shows as "OK"

ran my first backup with `barman backup node1 -- wait`

once that completed, when running `barman check node1` again I get the following error with  `empty incoming directory: FAILED`

```
barman@barman:~/node1/incoming$ barman check node1
Server node1:
        empty incoming directory: FAILED ('/var/lib/barman/node1/incoming' must be empty when archiver=off)
        PostgreSQL: OK
        is_superuser: OK
        PostgreSQL streaming: OK
        wal_level: OK
        replication slot: OK
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 2 backups, expected at least 0)
        pg_basebackup: OK
        pg_basebackup compatible: OK
        pg_basebackup supports tablespaces mapping: OK
        systemid coherence: OK
        pg_receivexlog: OK
        pg_receivexlog compatible: OK
        receive-wal running: OK
        archiver errors: OK
```

is this really an error?

**[pg.conf]**
```
[node1]
description =  "Our main PostgreSQL server"
conninfo = host=192.168.1.129 user=barman dbname=postgres
backup_method = postgres
streaming_conninfo = host=192.168.1.129 user=streaming_barman dbname=postgres
streaming_archiver = on
slot_name = barman
create_slot = auto
```

**[postgresql.auto.conf]**
```
listen_addresses = '*'
wal_level = 'replica'
max_wal_senders = '10'
max_replication_slots = '10'
archive_command = 'barman-wal-archive 192.168.1.109 node1 %p'
archive_mode = 'on'
```

please let me know what additional information you need to assist with this question.

**Comment by jeffjanes** [comment]
What do you mean by "really an error"?  This is not the type of error which will block you from taking a new backup.  But it is also clearly undesirable to have files endlessly piling up in "incoming" directory which will never be used, processed, or removed.

Why not just fix the problem?  What are you trying to accomplish by having both streaming and archive_command?  And if you are going to do that, why not just turn archiver on in your barman conf, so it works the way it was intended?

**Comment by dangelsaurus** [comment]
Hi Jeff, Thanks for the reply.

As you can probably tell, I'm new to Barman.  So please try to understand that.

> What do you mean by "really an error"? 
I mean, is this an error I should be concerned with?  Hence my asking the question here...

> Why not just fix the problem? What are you trying to accomplish by having both streaming and archive_command? And if you are going to do that, why not just turn archiver on in your barman conf, so it works the way it was intended?

I said I had followed the guide at http://docs.pgbarman.org/release/2.10/ where my understanding (and again, I'm new to Barman...) is that the strong recommendation was to use both Standard Archiving and WAL streaming...  If this is not correct, I'll be happy to stick with streaming.

My end goal is set this up with REPMGR (which I have working fine by itself) with Barman so that I can quickly spin up read-only servers during peak load times.

**Comment by jeffjanes** [comment]
> I said I had followed the guide at http://docs.pgbarman.org/release/2.10/ where my understanding (and again, I'm new to Barman...) is that the strong recommendation was to use both Standard Archiving and WAL streaming

You are right, I've never noticed (nor heeded, other than during testing) that advice.  But if you do follow it, you definitely should turn archiver=on in the conf file.  So in that sense it is really an error, in that it indicates you should make  a change.

Note that if you do follow the belt and suspenders approach and it pays off (you get different files from the two methods) then the discordant file is saved in the errors directory and will be reported to you, but you are then left on your own to figure out which version to believe, and what to do about it.

**Comment by dangelsaurus** [comment]
Thanks @jeffjanes. It's all sorta coming together now. I appreciate your taking the time to help me learn!
