### ISSUE TITLE
Never removed files from $PGDATA/pg_xlog/archive_status/*.done

### ISSUE THREAD

**Issue by xelite** [2ndquadrant-it/barman#28]
Got issue with a lot of old files in /var/lib/postgresql/*/main/pg_xlog/archive_status/*.done (>100k)

"archive_command": "rsync -a --remove-source-files %p barman@server:/var/lib/barman/client/incoming/%f", 

1. Whether barman uses this files? If yes, when?
2. Should I remove this files manually? (eg. post_backup_script)
3. Why barman doesn't do this itself?

**Comment by gbartolini** [comment]
This issue is not relevant as it is caused by improper usage of archive_command

**Comment by xelite** [comment]
Removed --remove-source-files from archive_command and works fine. Thanks for a tip.
