### ISSUE TITLE
Barman list-files shows only one timeline

### ISSUE THREAD

**Issue by speze88** [2ndquadrant-it/barman#29]
Hi,
is it intended behavior, that barman list-files only shows one timeline?

I have a master/slave postgres cluster running and thus after a failover the timeline changes. The wal shipping is working fine and is processed by barman cron correctly. However 

> barman list-files --target wal fsmpostgres 20160223T070002

 lists just the wal files from the previos timeline, e. g.

> /var/lib/barman/fsmpostgres/wals/0000000200000021/000000020000002100000089
> /var/lib/barman/fsmpostgres/wals/0000000200000021/00000002000000210000008A
> /var/lib/barman/fsmpostgres/wals/0000000200000021/00000002000000210000008B
> /var/lib/barman/fsmpostgres/wals/0000000200000021/00000002000000210000008C
> /var/lib/barman/fsmpostgres/wals/0000000200000021/00000002000000210000008D
> /var/lib/barman/fsmpostgres/wals/0000000200000021/00000002000000210000008E
> /var/lib/barman/fsmpostgres/wals/0000000200000021/00000002000000210000008F
> /var/lib/barman/fsmpostgres/wals/00000003.history

The existing directory with new timelines /var/lib/barman/fsmpostgres/wals/0000000300000021 is obviously being ignored. I tried to rebuild the xlog, but this didn't change anything.

As a result the icinga check for monitoring the last-wal is failing, because wal files of the new timeline are not taken into consideration.

**Comment by gbartolini** [comment]
Fixed by 1f83e21818caa5991a8970c80a9a870c4348f5f8
