### ISSUE TITLE
Barman work with BDR?

### ISSUE THREAD

**Issue by longnguyen11288** [2ndquadrant-it/barman#4]

**Comment by gbartolini** [comment]
Yes, you can backup a BDR node with Barman.

**Comment by alessandroG77** [comment]
Hi gabriele,
i'm Alessandro from Eidosmedia company in Milan.

I'm implementing Barman Backup (ver 2.0) with 2 bdr Postgres server (as you say last 9.4 patched).

I want to say if i need some changes in barman conf for backup every node.

In every bdr node i have:

$ vim $PG_DATA/postgresql.conf
 
[...]
 
wal_level = 'archive'
archive_mode = on
archive_command = 'rsync -a %p barman@m1srpl-Barman01:$INCOMING_WAL_DIRECTORY/%f'
 
[...]


thanks a lot,
best,
Alessandro.

**Comment by alessandroG77** [comment]
Any news?
