### ISSUE TITLE
PostgreSQL failed to start after barman recover 

### ISSUE THREAD

**Issue by ops-dba** [2ndquadrant-it/barman#42]
We have a PostgreSQL replication cluster consisting of a primary server and several standby servers, and we use Barman 1.6 on a separate server to manage our backups. The primary PG server is configured to archive WAL files to the barman server. We also run base backups of the primary server from the barman server.

Recently, we upgraded the PG replication cluster from 9.4 to 9.5. After the upgrade to 9.5, WAL file archiving resumed without any issues, and base backups completed successfully. We validate our backups by performing "barman recover" operations from the barman server to a remote server. Although the barman recover command ran successfully, PostgreSQL failed to start on the remote host. Error from the PG log: FATAL,XX000,"could not locate required checkpoint record"

I checked the output from the barman recover command, and couldn't find the Begin WAL or End WAL files anywhere on the barman server. Investigating further, I checked the barman wals folder on the barman server, and discovered that 9.5 WAL files reported as being archived in our barman.log file no longer exist in the wals folder. However, all of the WAL files that were archived for 9.4 exist in the wals folder. Apparently, barman deleted the 9.5 WAL files after we take our nightly base backup of the primary server. 

barman check z-prod
Server z-prod:
	PostgreSQL: OK
	wal_level: OK
	directories: OK
	retention policy settings: OK
	backup maximum age: OK (no last_backup_maximum_age provided)
	compression settings: OK
	failed backups: OK (there are 0 failed backups)
	minimum redundancy requirements: OK (have 18 backups, expected at least 0)
	ssh: OK (PostgreSQL server)
	not in recovery: OK
	archive_mode: OK
	archive_command: OK
	continuous archiving: OK
	archiver errors: OK

**Comment by gbartolini** [comment]
In Barman terms' those two servers should be treated as separate servers, as there is no continuum as far as recovery is concerned. If you treat them as a single server, you should have performed a base backup immediately after the upgrade.
