### ISSUE TITLE
barman 2.0  base backup not working  for postgrersql 9.6

### ISSUE THREAD

**Issue by toplinuxsir** [2ndquadrant-it/barman#59]
barman 2.0  base backup not working  for postgrersql 9.6
as the server version is 9.6 (server pg9.6)
and run :

barman backup pg9.6 

will block , and never return !

**Comment by mnencia** [comment]
This issue is incomplete, I'm closing it. Please follow the troubleshooting procedure documented at http://docs.pgbarman.org/release/2.0/#troubleshooting
