### ISSUE TITLE
Doing backup-recover on the same destination directory rewrite the WALs

### ISSUE THREAD

**Issue by florentx** [2ndquadrant-it/barman#6]
I ran the same `backup recover` command again, after 30 minutes, and I noticed that the rsync command transfer only the changed files, except for the `pg_xlog/` content, which is purged and rewritten on the destination server.

The recovery could be faster, if we preserved the WALs when launching the command again.

Maybe the `pg_xlog` content could be appended to the `exclude_and_protect` variable for rsync.

**Comment by mnencia** [comment]
It could be improved, but the code is not so straight-forward, as the copy process is split in batches. However, in most cases, the right approach is to enable the `get-wal` recovery options, to avoid completely the WAL files copy during the recovery.

**Comment by florentx** [comment]
Thank you for this trick. `get-wal` rules.
