### ISSUE TITLE
backup for postgresql 9.6 will block and not return 

### ISSUE THREAD

**Issue by toplinuxsir** [2ndquadrant-it/barman#60]
If you use barman 2.0 to do backup for postgresql 9.6 It will block for a long time the bakcup status always is :"STARTED", 
barman check is OK .

**Comment by toplinuxsir** [comment]
The output is as below:
  Starting backup using postgres method for server pg96 in /backdisk/barman/pg96/base/20161014T143049
Backup start at xlog location: 0/A7001B80 (0000000100000000000000A7, 00001B80)
Copying files.

**Comment by mnencia** [comment]
Could you please attach the "barman diagnose" output to this issue?

**Comment by toplinuxsir** [comment]
This is the postgresql 9.6 diangose info, the backup status always is STARTED:
"pg96": {
           "backups": {
               "20161014T081503": {
                   "backup_id": "20161014T081503",
                   "backup_label": null,
                   "begin_offset": 44288,
                   "begin_time": "Fri Oct 14 08:15:33 2016",
                   "begin_wal": "00000001000000000000008E",
                   "begin_xlog": "0/8E00AD00",
                   "config_file": "/etc/postgresql/9.6/main/postgresql.conf",
                   "deduplicated_size": null,
                   "end_offset": null,
                   "end_time": null,
                   "end_wal": null,
                   "end_xlog": null,
                   "error": null,
                   "hba_file": "/etc/postgresql/9.6/main/pg_hba.conf",
                   "ident_file": "/etc/postgresql/9.6/main/pg_ident.conf",
                   "included_files": null,
                   "mode": "postgres",
                   "pgdata": "/s1/postgresql/9.6/main/data",
                   "server_name": "pg96",
                   "size": null,
                   "status": "STARTED",
                   "tablespaces": null,
                   "timeline": 1,
                   "version": 90600
               }
           },
           "config": {
               "active": true,
               "archiver": true,
               "archiver_batch_size": 0,
               "backup_directory": "/backdisk/barman/pg96",
               "backup_method": "postgres",
               "backup_options": "concurrent_backup",
               "bandwidth_limit": null,
               "barman_home": "/backdisk/barman",
               "barman_lock_directory": "/backdisk/barman",
               "basebackup_retry_sleep": 300,
               "basebackup_retry_times": 3,
               "basebackups_directory": "/backdisk/barman/pg96/base",
               "check_timeout": 30,
               "compression": null,
               "conninfo": "host=10.11.12.236 port=5433 user=repluser dbname=postgres password=pass123",
               "custom_compression_filter": null,
               "custom_decompression_filter": null,
               "description": "Zhengzhou Postgresql Database (Streaming-Only)",
               "disabled": false,
               "errors_directory": "/backdisk/barman/pg96/errors",
               "immediate_checkpoint": false,
               "incoming_wals_directory": "/backdisk/barman/pg96/incoming",
               "last_backup_maximum_age": null,
               "minimum_redundancy": 2,
               "msg_list": [],
               "name": "pg96",
               "network_compression": false,
               "path_prefix": "/usr/lib/postgresql/9.6/bin",
               "post_archive_retry_script": null,
               "post_archive_script": null,
               "post_backup_retry_script": null,
               "post_backup_script": "/backdisk/barman_script/post_backup_script.sh",
               "pre_archive_retry_script": null,
               "pre_archive_script": null,
               "pre_backup_retry_script": null,
               "pre_backup_script": null,
               "recovery_options": "",
               "retention_policy": "window 7 w",
               "retention_policy_mode": "auto",
               "reuse_backup": null,
               "slot_name": "barman_backup1",
               "ssh_command": null,
               "streaming_archiver": true,
               "streaming_archiver_batch_size": 0,
               "streaming_archiver_name": "barman_receive_wal",
               "streaming_backup_name": "barman_streaming_backup",
               "streaming_conninfo": "host=10.11.12.236 port=5433 user=repluser dbname=postgres password=pass123",
               "streaming_wals_directory": "/backdisk/barman/pg96/streaming",
               "tablespace_bandwidth_limit": null,
               "wal_retention_policy": "simple-wal 7 w",
               "wals_directory": "/backdisk/barman/pg96/wals"
           },
           "status": {
               "archive_command": "/bin/false",
               "archive_mode": "on",
               "archived_count": 0,
               "config_file": "/etc/postgresql/9.6/main/postgresql.conf",
               "connection_error": null,
               "current_archived_wals_per_second": 0.0,
               "current_size": 1759448444.0,
               "current_xlog": "000000010000000000000098",
               "data_directory": "/s1/postgresql/9.6/main/data",
               "failed_count": 7348,
               "hba_file": "/etc/postgresql/9.6/main/pg_hba.conf",
               "ident_file": "/etc/postgresql/9.6/main/pg_ident.conf",
               "is_archiving": null,
               "is_superuser": true,
               "last_archived_time": null,
               "last_archived_wal": null,
               "last_failed_time": "Sat Oct 15 08:08:39 2016",
               "last_failed_wal": "000000010000000000000001",
               "pg_basebackup_bwlimit": true,
               "pg_basebackup_compatible": true,
               "pg_basebackup_installed": true,
               "pg_basebackup_path": "/usr/lib/postgresql/9.6/bin/pg_basebackup",
               "pg_basebackup_tbls_mapping": true,
               "pg_basebackup_version": "9.6.0",
               "pg_receivexlog_compatible": true,
               "pg_receivexlog_installed": true,
               "pg_receivexlog_path": "/usr/lib/postgresql/9.6/bin/pg_receivexlog",
               "pg_receivexlog_supports_slots": true,
               "pg_receivexlog_synchronous": false,
               "pg_receivexlog_version": "9.6.0",
               "pgespresso_installed": false,
               "replication_slot": [
                   "barman_backup1",
                   true,
                   "0/9801AA50"
               ],
               "replication_slot_support": true,
               "server_txt_version": "9.6.0",
               "stats_reset": "Thu Oct 13 15:41:31 2016",
               "streaming": true,
               "streaming_supported": true,
               "synchronous_standby_names": [
                   ""
               ],
               "systemid": "6340851260704114378",
               "timeline": 1,
               "wal_level": "logical",
               "xlogpos": "0/9801F860"
           }
       }

**Comment by gbartolini** [comment]
Why is 'archive_command' set to 'false'?

**Comment by toplinuxsir** [comment]
OK, I got it , thanks !
