### ISSUE TITLE
pg_replslot should be excluded from backups

### ISSUE THREAD

**Issue by mhagander** [2ndquadrant-it/barman#65]
Barman seems to include the `pg_replslot` directory in the base backups. This is not good as it can lead to issues of WAL retention after restore. See the PostgreSQL documentation at https://www.postgresql.org/docs/9.6/static/continuous-archiving.html#BACKUP-BASE-BACKUP

**Comment by gbartolini** [comment]
Thanks Magnus!

**Comment by mhagander** [comment]
And thanks to you for a quick fix! :)
