### ISSUE TITLE
Doc about limitations on .partial files

### ISSUE THREAD

**Issue by gbartolini** [2ndquadrant-it/barman#79]
The section about "Limitations of partial WAL files with recovery" has gone lost in transition to version 2.0 of Barman, as pointed out by Nick Barnes on the support mailing list.

See: http://docs.pgbarman.org/release/1.6.1/#limitations-of-partial-wal-files-with-recovery

**Comment by dawncold** [comment]
copy partial WAL to pg_wal is the responsibility of DBA?

**Comment by eLBati** [comment]
A couple of unanswered questions anyway:
https://github.com/2ndquadrant-it/barman/issues/79#issuecomment-375226459
https://github.com/2ndquadrant-it/barman/issues/92#issuecomment-286371957

**Comment by mnencia** [comment]
I believe that the commit https://github.com/2ndquadrant-it/barman/commit/87e94616556e332d42ed453ba3f10b26fc122a4f contains the required addition to the documentation.
The long story short: at the moment copying the .partial is responsibility of DBA, and this is a current Barman limitation that could be lifted in the future.

**Comment by eLBati** [comment]
ok @mnencia thanks
