### ISSUE TITLE
possible race condition between pg_receivexlog and "barman cron"

### ISSUE THREAD

**Issue by costela** [2ndquadrant-it/barman#82]
Hi,

I believe there might be a race condition between `pg_receivexlog` and `barman cron` when using streaming replication on postgresql 9.6.
During normal operation `pg_receivexlog` creates `.tmp` files in the `streaming` folder. If `barman cron` happens to run while this file exists, it gets pulled from under `pg_receivexlog`'s feet and moved to the `errors` folder. 

Relevant log entries:
```
01:18:01,636 [2521] barman.server INFO: Starting receive-wal for server pg-db1                 
01:18:01,636 [2520] barman.wal_archiver INFO: No xlog segments found from streaming for pg-db1.
01:18:01,691 [2521] barman.wal_archiver INFO: Activating WAL archiving through streaming protocol
01:18:02,262 [2521] barman.command_wrappers INFO: pg-db1: pg_receivexlog: starting log streaming at 16A9/4C000000 (timeline 2)
(...)
01:19:01,818 [2649] barman.wal_archiver INFO: No xlog segments found from streaming for pg-db1.
01:19:01,818 [2649] barman.wal_archiver WARNING: Archiver is about to move 1 unexpected file(s) to errors directory for pg-db1 from streaming
01:19:01,818 [2649] barman.wal_archiver WARNING: Moving unexpected file for pg-db1 from streaming: 00000002.history.tmp
(...)
01:20:22,901 [2521] barman.command_wrappers INFO: pg-db1: pg_receivexlog: could not rename file "/var/lib/barman/pg-db1/streaming/00000002.history.tmp" to "/var/lib/barman/pg-db1/streaming/00000002.history": No such file or directory
01:20:24,180 [2521] barman.command_wrappers INFO: pg-db1: pg_receivexlog: finished segment at 16A9/4D000000 (timeline 2)
01:20:25,315 [2521] barman.command_wrappers INFO: pg-db1: pg_receivexlog: finished segment at 16A9/4E000000 (timeline 2)
```

Note that between 01:18:02 and 01:20:22 `pg_receivexlog` (PID 2521) didn't do much, but `barman cron` got called and moved the `*.tmp` file away as an error.

This seems to happen only right after starting `pg_receivexlog`. As long as it's running uninterrupted, the problem doesn't seem to occur (I assume `pg_receivexlog` only generates a `.history` file while initializing).
I can't imagine any reason why `pg_receivexlog` would hang for 2:20 minutes between creating and moving the `.history.tmp` file (especially since it doesn't seem to do much to it, as seen [here](https://github.com/postgres/postgres/blob/REL9_6_STABLE/src/bin/pg_basebackup/receivelog.c#L319,L362)), but that's probably a separate issue. The race-condition would still be there (even if considerably harder to hit :wink:).

Cheers

**Comment by mnencia** [comment]
fixed in commit ffc3cca6 (Released in Barman 2.3)
