### ISSUE TITLE
change configuration file warning to an info message

### ISSUE THREAD

**Issue by foozmeat** [2ndquadrant-it/barman#83]
I run `barman -q backup` via cron but every run produces the following warning:

```
WARNING: pg_basebackup does not copy the PostgreSQL configuration files that reside outside PGDATA. Please manually backup the following files:
        /etc/postgresql/9.5/main/postgresql.conf
        /etc/postgresql/9.5/main/pg_hba.conf
        /etc/postgresql/9.5/main/pg_ident.conf
```

Unfortunately this warning is sent to `stderr` so piping output to `/dev/null` doesn't silence it. I would like to request that this be changed to use the `INFO` log level. It's a message that the user only needs to see once to understand what they need to do. During normal operation they don't need to be reminded about it.

**Comment by mnencia** [comment]
Closed with 738c0e8 
It ads an option to acknoledge the warning and remove it.
