### ISSUE TITLE
barman recover does not copy partial streaming WAL

### ISSUE THREAD

**Issue by eLBati** [2ndquadrant-it/barman#92]
barman 2.1
WAL archiving with streaming connection

Current WAL status:
```
$ ls wals/0000000100000002/
000000010000000200000042  000000010000000200000043  000000010000000200000044
$ ls streaming/
000000010000000200000045.partial
```

Trying to recover with
```
barman recover --remote-ssh-command 'ssh postgres@POSGRESSERVER' POSGRESSERVER 20170312T012319 /tmp/test_restore --target-time '2017-03-13 12:00:00'
```
Then, after starting the restored cluster:
```
cp: cannot stat 'barman_xlog/000000010000000200000045': No such file or directory
[...]
2017-03-13 12:18:18 CET [4693-9] LOG:  last completed transaction was at log time 2017-03-13 01:07:49.849534+01
```
Indeed, in the restored DB, I can't find changes made this morning.

But, if I manually copy ```000000010000000200000045.partial``` to ```barman_xlog/000000010000000200000045``` before starting the recovered cluster, I can correctly restore the given target time:
```
2017-03-13 12:56:49 CET [11374-11] LOG:  last completed transaction was at log time 2017-03-13 11:34:33.112172+01
```

Additional info at http://dba.stackexchange.com/questions/163883/pgbarman-recover-from-streaming-backup

**Comment by eLBati** [comment]
Noticed now https://github.com/2ndquadrant-it/barman/issues/79
Can't ```.partial``` files be handled by barman directly?

**Comment by mnencia** [comment]
Duplicated by #79
