### ISSUE TITLE
BDR Wals with Barman

### ISSUE THREAD

**Issue by alessandroG77** [2ndquadrant-it/barman#93]
Hi Gabriele,
here Alessandro from Eidosmedia.

I need to say:
which wal attribute i use to works with Barman?

Archive or Logical?

I' ve 3 bdr nodes postgre 9.4 bdr and Barman 2.0

Thanks,
Alessandro.

**Comment by mnencia** [comment]
The only WAL level that is not compatible with Barman is `wal_level = minimal`. Everything else works at the moment.
